### ISSUE TITLE
Error while loading shared libraries: libKMotionX.so

### ISSUE THREAD

**Issue by toransahu** [parhansson/KMotionXCNC#2]
I've installed KMotionX successfully and was executing
```bash
$ kmxWeb -document_root ./
```
But I got following error
```bash
[INFO] (KMotionX.cpp:117) Using KMOTIONX_HOME=/home/toran/.kmotionx
[INFO] (KMotionX.cpp:146) Launching KMotionServer: '/home/toran/.kmotionx/bin/KMotionServer &'
/home/toran/.kmotionx/bin/KMotionServer: error while loading shared libraries: libKMotionX.so: cannot open shared object file: No such file or directory
```

**Comment by parhansson** [comment]
Depending on platform 
```make install```
might have to be executed as super user
```sudo make install```

It seems like you run some kind of linux distribution?

**Comment by parhansson** [comment]
This one seems dead. Most probably the problem is that  [KMotionX](https://github.com/parhansson/KMotionX)  is not installed and need to be installed first.
I should update readme file
